version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: library_db
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
      POSTGRES_DB: library_db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U library_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
